digraph {
    teplota [shape=record, label="teplota|{teplota=0.4325|den=0.1454|obdobi=0.1482|vhkost=0.2964}"]
    teplota -> den [label="stredni {1,3,4,6,8,9,14,15}"]
    den [shape=record, label="den|{den=0.6556|obdobi=0.4669|vhkost=0.056}"]
    den -> obdobi [label="svatek {1,6,8,14}"]
    obdobi [shape=record, label="obdobi|{obdobi=0.8113|vhkost=0}"]
    obdobi -> Nizka [label="zima {1}"]
    Nizka [shape=box, style=rounded, label="Nizka"]
    obdobi -> Nizka2 [label="podzim {6}"]
    Nizka2 [shape=box, style=rounded, label="Nizka"]
    obdobi -> Velka [label="jaro {8}"]
    Velka [shape=box, style=rounded, label="Velka"]
    obdobi -> Nizka3 [label="leto {14}"]
    Nizka3 [shape=box, style=rounded, label="Nizka"]
    den -> Stredni [label="vikend {3}"]
    Stredni [shape=box, style=rounded, label="Stredni"]
    den -> Nizka4 [label="pracovni {4,9,15}"]
    Nizka4 [shape=box, style=rounded, label="Nizka"]
    teplota -> obdobi2 [label="vysoka {2,10,11,12,13}"]
    obdobi2 [shape=record, label="obdobi|{den=0.571|obdobi=1.1219|vhkost=0.7219}"]
    obdobi2 -> Stredni2 [label="zima {2}"]
    Stredni2 [shape=box, style=rounded, label="Stredni"]
    obdobi2 -> vhkost [label="leto {10,11}"]
    vhkost [shape=record, label="vhkost|{den=0|vhkost=1}"]
    vhkost -> Velka2 [label="mala {10}"]
    Velka2 [shape=box, style=rounded, label="Velka"]
    vhkost -> Nizka5 [label="velka {11}"]
    Nizka5 [shape=box, style=rounded, label="Nizka"]
    obdobi2 -> Stredni3 [label="jaro {12}"]
    Stredni3 [shape=box, style=rounded, label="Stredni"]
    obdobi2 -> Velka3 [label="podzim {13}"]
    Velka3 [shape=box, style=rounded, label="Velka"]
    teplota -> Velka4 [label="nizka {5,7}"]
    Velka4 [shape=box, style=rounded, label="Velka"]
}
