#
# @file Makefile
#
# Tests for IPP interpret
#
# @author <xblaze38> Michal Blažek
# 

all: run

run:
	./tester.sh

clean:
	rm -f ./tests/*.your_out
	rm -f ./tests/*.your_rc
	rm -f ./tests/*.out_diff
	rm -f ./tests/*.rc_diff
