# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:

#command to include the .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 8.x
#command to include maui
- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    projects: '**\InformationSystem.sln'

- task: DotNetCoreCLI@2
  name: 'Test'
  inputs:
    command: 'test'
    projects: '**\InformationSystem.sln'